# Generated by Django 3.2 on 2021-09-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('login', '0002_auto_20210909_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_File_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='文件')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('file_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='login.user')),
            ],
        ),
    ]
