# Generated by Django 3.2 on 2021-09-10 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('affair', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submit_file_model',
            options={'ordering': ['-submit_time'], 'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
    ]
